version: '3'

services:
  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
      - '"27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
      - MONGODB_HOST=mongodb
    depends_on:
      - rabbitmq
      - mongodb
    command: ["npm", "start"]

  service:
    build: ./service2
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
      - MONGODB_HOST=mongodb
    restart: on-failure
    command: ["node", "receive.js"]
    depends_on:
      - rabbitmq
      - mongodb